language: cpp
dist: xenial
sudo: false


matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL = "CC=gcc-8 && CXX=g++-8"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-8
      env:
        - MATRIX_EVAL = "CC=clang-8 && CXX=clang++-8"

before_install:
  - eval "${MATRIX_EVAL}"
