language: cpp
dist: xenial
sudo: false

matrix:
  include:
    - name: g++-8
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      install:
        - pip install --user conan
      script:
        - conan install . -pr conan_profiles/linux_gcc
        - CXX=g++-8 cmake .
        - cmake --build . -- -j$(nproc)
        - ctest --output-on-failure

    - name: clang-8
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test  # for libstdc++
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
            - clang-tidy-8
            - libstdc++-8-dev  # for <filesystem>
      install:
        - pip install --user conan
      script:
        - conan install .  -pr conan_profiles/linux_clang
        - CXX=clang++-8 cmake .
        - cmake --build . -- -j$(nproc)
        - ctest --output-on-failure
