language: cpp
dist: xenial
sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libasio-dev
      script:
        - CXX=g++-8 cmake .
        - cmake --build .

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-7
            - libasio-dev
      script:
        - CXX=clang++-7 cmake .
        - cmake --build .
