language: cpp
dist: bionic
sudo: false

matrix:
  include:
    - name: g++-9
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      install:
        - pip install --user conan
      script:
        - CXX=g++-9 CC=gcc-9 conan install . -pr conan_profiles/linux_gcc --build
        - CXX=g++-9 cmake .
        - cmake --build . -- -j$(nproc)
        - ctest --output-on-failure

    - name: clang-10
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test  # for libstdc++
            - llvm-toolchain-bionic-10
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
            - clang-tidy-10
            - libstdc++-10-dev  # for <filesystem>
      install:
        - pip install --user conan
      script:
        - CXX=clang++-10 CC=clang-10 conan install .  -pr conan_profiles/linux_clang --build
        - CXX=clang++-10 cmake .
        - cmake --build . -- -j$(nproc)
        - ctest --output-on-failure
