language: cpp
dist: xenial
sudo: false

matrix:
  include:
    - name: g++-8
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libasio-dev
            - libboost-dev
      script:
        - CXX=g++-8 cmake .
        - cmake --build .

    - name: clang-8
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-7
            - libasio-dev
            - libboost-dev
      script:
        - CXX=clang++-7 cmake .
        - cmake --build .
