name: Build and test
on: [push, workflow_dispatch]
jobs:
  build_and_test:
    strategy:
      matrix:
        compiler: [ {type: clang, bin: clang++, ver: 14}, {type: gcc, bin: g++, ver: 11} ] 

    runs-on: ubuntu-22.04
    env:
      BUILD_TYPE: Release
      CXX: ${{ matrix.compiler.bin }}-${{ matrix.compiler.ver }}
    steps:
    - uses: actions/checkout@v3

    - name: Apt install
      run: sudo apt install ninja-build

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0
      
    - name: Create default profile
      run: conan profile new default
    
    - name: Update profile
      run: |
        conan profile update settings.os=Linux default
        conan profile update settings.arch=x86_64 default
        conan profile update settings.compiler=${{ matrix.compiler.type}} default
        conan profile update settings.compiler.version=${{ matrix.compiler.ver }} default
        conan profile update settings.compiler.libcxx=libstdc++11 default
      
    - name: Install dependencies
      run: conan install . -s build_type=${{env.BUILD_TYPE}} --install-folder=${{github.workspace}}/build --build missing

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -GNinja -DDISABLE_LTO=ON -DUSE_CLANG_TIDY=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - name: Tests
      run: ctest --output-on-failure
