name: Build and test
on: [push]
jobs:
  build_and_test:
    strategy:
      matrix:
        compiler: [clang]

    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Release
    steps:
    - uses: actions/checkout@v3

    - name: Install compiler
      run: apt install clang-12 clang-tidy-12

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0
      
    - name: Create default profile
      run: conan profile new default
    
    - name: Update profile
      run: |
        conan profile update settings.compiler=clang default
        conan profile update settings.compiler.version=12 default
        conan profile update settings.compiler.libcxx=libstdc++11 default
      
    - name: Install dependencies
      run: conan install . -s build_type=${{env.BUILD_TYPE}} --install-folder=${{github.workspace}}/build

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
